### ISSUE TITLE
module incompatible with npm 3

### ISSUE THREAD

**Issue by AurelioDeRosa** [mlucool/gulp-jsdoc3#1]
The module tries to load `jsdoc` inside the `gulp-jsdoc3` folder. In npm 3 the dependencies are installed in a flat structure and this causes an error.

**Comment by mlucool** [comment]
Thanks for the bug report! This is now fixed in 0.0.3 see: https://github.com/mlucool/gulp-jsdoc3/commit/fb198746b2532bc449433b79f6dd6fa25e7f5dbf
