### ISSUE TITLE
Is it possible to change the theme?

### ISSUE THREAD

**Issue by TxHawks** [mlucool/gulp-jsdoc3#11]
I'm trying to change the theme used for the generated docs, but without much success.

I've installed another theme using npm (`jsdoc-oblivion`), and change the `path` and `theme` properties, but with no effect.

**Comment by mlucool** [comment]
Hi,

This issue was fixed with https://github.com/mlucool/gulp-jsdoc3/pull/7 which I plan to release sometime early next week. Otherwise, you can depend on the project via git instead of npm to test it out.

**Comment by mlucool** [comment]
Released. Is this issue fixed?

**Comment by mlucool** [comment]
Closing, please re-open if there is still an issue.

**Comment by pixelass** [comment]
I have the same issue. I tried a few themes and nothing works. It was driving me crazy until I found this issue.

if it works can you please provide an example. I tried the following.

* used jsdoc.json
* used inline options

**Comment by dudesweet100** [comment]
How do you change the theme and path? I want to use loke-jsdoc-theme.

**Comment by AndrewGuenther** [comment]
@dudesweet100 Using a different theme is covered in the README.

https://github.com/mlucool/gulp-jsdoc3/blob/master/README.md#overriding-the-default-layout

**Comment by dudesweet100** [comment]
I dont understand, how would the configuration then look like when using https://github.com/LOKE/jsdoc-theme.

````
 "templates": {
        "default": {
            // Set my own layout file
            "layoutFile": "./node_modules/loke-jsdoc-theme"
        }
    }
````

Tried this and it does not work, it expects a file.

**Comment by pixelass** [comment]
@dudesweet100 make sure the config is valid JSON (no comments). Also don't confuse `templates` with `opts/template`

 The first allows to change the template for a specific type while the other offers to change the path to your actual theme

 Here's a working example for one of my repos: https://github.com/pixelass/schachtel/blob/master/jsdoc.json#L23
