### ISSUE TITLE
Is it compatible with angular docs ?

### ISSUE THREAD

**Issue by kevincaradant** [mlucool/gulp-jsdoc3#12]
Hi,

Sorry to ask something about angularJS but i don't found documentation about this. If i use @ngdocs controller , that seems doesn't work :/

i'm a little bit confused between ngdocs , jsdocs etc 

Thank you :)

**Comment by mlucool** [comment]
I have not used it, but it looks like you can try out https://github.com/allenhwkim/angular-jsdoc and instead of what they have for gulp, use this project and put all the params in a file.

**Comment by kevincaradant** [comment]
Thank you, finally i look on ngdocs , that seems to be more adapted for my needs , if one day your plugin has the annotates for ngdocs ( angularjs ) , that will be with pleasure that i come again on your plugin that seems to be very helpfull , simple and very pretty  :)

**Comment by mlucool** [comment]
No problem!
