### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by systemaker** [mlucool/gulp-jsdoc3#16]
hello, when I run "npm install" , i have this issue : 

npm ERR! node v4.2.4
npm ERR! npm  v3.8.5

npm ERR! No compatible version found: gulp-jsdoc3@~3.4.0
npm ERR! Valid install targets:
npm ERR! 0.2.1, 0.2.0, 0.1.1, 0.1.0, 0.0.3, 0.0.2, 0.0.1

**Comment by mlucool** [comment]
Hi,

Per the error message, the newest version is 0.2.1. Are you sure your package.json has the right version number in it?

**Comment by systemaker** [comment]
done, thanks.

**Comment by mlucool** [comment]
np
