### ISSUE TITLE
do not support jaguarjs-jsdoc

### ISSUE THREAD

**Issue by likezero** [mlucool/gulp-jsdoc3#17]
It is not work with jaguarjs-jsdoc. 
src/jsdocConfig.json
```javascript
{
  "tags": {
    "allowUnknownTags": true
  },
  "source": {
    "excludePattern": "(^|\\/|\\\\)_"
  },
  "opts": {
    "destination": "./docs/gen"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false,
    "default": {
      "outputSourceFiles": true
    },
    "path": "ink-docstrap", // here, i changed to jaguarjs-jsdoc, but it don't work .
    "theme": "cerulean",
    "navType": "vertical",
    "linenums": true,
    "dateFormat": "MMMM Do YYYY, h:mm:ss a"
  }
}
```

i can not find any code to process `templates.path`, but in file 'gulp-jsdoc3/dist/gulp-jsdoc.js', i find this: 
```javascript
 // Config + ink-docstrap if user did not specify their own layout
   if (!jsdocConfig.templates || !jsdocConfig.templates.default || !jsdocConfig.templates.default.layoutFile) {
        args = args.concat(['-t', inkdocstrap]);
   }
```

**Comment by mlucool** [comment]
Hi,

Can you removing the line: ``args = args.concat?``
Then add the following to your config:
```javascript
  "opts": {
    "destination": "./docs/gen",
    "template": "/full/path/to/..../node_modules/jaguarjs-jsdoc"
  },
```
Per: http://usejsdoc.org/about-configuring-jsdoc.html#incorporating-command-line-options-into-the-configuration-file

If that works, I'll add a fix. I noticed that jaguarjs-jsdocs does produce an index that is similar to ink-docstrap in that it is missing my modules when I do it like that. Not sure if that's intended or not.

**Comment by fluky** [comment]
I had the same issue, commenting out
```
args = args.concat(['-t', inkdocstrap]);
```

And using
```
template: 'node_modules/docdash'
```

Worked for me.  Look forward to a fix.

**Comment by producerism** [comment]
Same here, commenting out the args.concat line, and passing in an opt.template works for me as well. Would love to see a fix as well.

**Comment by dudesweet100** [comment]
Was this fixed? How can someone use a different theme?
