### ISSUE TITLE
incorrect test for custom layout

### ISSUE THREAD

**Issue by karimsa** [mlucool/gulp-jsdoc3#18]
It is difficult to fix #17 with an incorrect test (a stream is being treated like a promise).

EDIT: I removed the log as it pertained towards a different test.

The handling of the stream is incorrect on lines 105-123.

**Comment by mlucool** [comment]
Yes I agree, that does look like the incorrect usage of promises. Can you make a PR to fix?

**Comment by karimsa** [comment]
Yes, I am working on it on my fork.
