### ISSUE TITLE
ENAMETOOLONG

### ISSUE THREAD

**Issue by StarpTech** [mlucool/gulp-jsdoc3#25]
Hi
I want to build a big project. I run into this issue. Thank you.

Windows 10
Nodejs 4
npm 3.8.0

```
[13:59:07] Starting 'doc'...
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:874:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at D:\me\CodeRepository\webapp\node_modules\gulp-jsdoc3\dist\gulp-jsdoc.js:112:51
    at D:\me\CodeRepository\webapp\node_modules\karma\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by StarpTech** [comment]
As a workaround you can pass the source parameter in the jcdoc.json but this makes this plugin a little bit useless.

```js
  var jsdoc = require('gulp-jsdoc3');

  gulp.task('doc', function (cb) {
    var config = require(options.root + '/jsdoc.json');
    gulp.src([], { read: false })
      .pipe(jsdoc(config, cb));
  });
```

```json
  "source": {
    "include": [
      "./lib/assets_dev/static/components"
    ],
    "exclude": [
      "node_modules",
      "bower_components"
    ]
  },
```

**Comment by mlucool** [comment]
Hi,

A quick look at the docs and I don't see a better way than what you propose (which I agree makes gulp almost useless). Do you have any suggestions?

**Comment by AndrewGuenther** [comment]
ENAMETOOLONG is a system limitation. Unless you can pass all of the files to `jsdoc` some other way, this can't be resolved.

Alternatively, you could call into jsdoc directly rather than doing a spawn and populating the `args` parameter yourself. That could work? I may take a stab at it.

**Comment by AndrewGuenther** [comment]
Wait, what about taking the filenames in the source stream and populating the config object in code? Just append it to the arguments that are already passed in.

**Comment by AndrewGuenther** [comment]
Just hacked this together a bit. Works like a charm. I will post a PR once things are cleaned up and tests are fixed.

@mlucool do you have any preference on what the behavior should be if `source.include` is already specified in the `config` parameter?

**Comment by mlucool** [comment]
If source.include is there, I would imagine that takes precedence unless there is a way to do a clean merge. For things like this, there needs to be a way to opt in/out. Not clear which one this would be, but I would say opt out if 99% of people would want this feature, which I think they would. Looking forward to the PR.
