### ISSUE TITLE
Is there any way to make jsDoc parse more than one .md file ?

### ISSUE THREAD

**Issue by Avcajaraville** [mlucool/gulp-jsdoc3#28]
On our project, we do have several md files that explains different parts of the app.

Would be possible to add this feature or it is there already ?

If we pass a glob pointing to our md folder (where all of our md files are), gulp-jsdoc only uses the last one there.

Thanks !

**Comment by mlucool** [comment]
We just pass all the glob to jsdoc. This question is better suited to the package we are a thin wrapper over:  https://github.com/jsdoc3/jsdoc/

**Comment by Avcajaraville** [comment]
I will say, just for the sake of document it, and maybe to help others who might have this issue as well, that I'm using now [tutorials](http://usejsdoc.org/about-tutorials.html).

It is not a perfect solution, but definitely helps to achieve my goal. This, combined with a custom template, creates just what I was looking for.

**Comment by mlucool** [comment]
Updated README: https://github.com/mlucool/gulp-jsdoc3/commit/af939b48d9556e48e037540e87fb398ce06a24da

Thanks for the note!

**Comment by Avcajaraville** [comment]
Great, happy that my note helped :)
