### ISSUE TITLE
wrench.js is deprecated

### ISSUE THREAD

**Issue by hipio** [mlucool/gulp-jsdoc3#29]
`npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.`

Please update/change your code to use fs-extra as suggested. 😄

**Comment by AndrewGuenther** [comment]
Hey @hipio,

Wrench is a transitive dependency brought in by jsdoc itself, it is not within the power of this project's maintainer to remove it.

**Comment by mlucool** [comment]
@AndrewGuenther is correct. Closing as there is nothing I can do
