### ISSUE TITLE
in windows 7 it's ok,but in linux(including mac), report some errors.

### ISSUE THREAD

**Issue by priscillapan** [mlucool/gulp-jsdoc3#31]
Starting 'document-output'...
[17:26:55] Finished 'document-output' after 59 ms
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at /home/project/node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js:112:121
    at /home/project/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by mlucool** [comment]
EACCESS is typically a permission issues. Check you have access to all the files and where it is trying to write

**Comment by priscillapan** [comment]
in Mac, sudo gulp document-output, the same error occured. i'v checked the directory it's trying to write,  it has w/r  right

**Comment by mlucool** [comment]
EACCES is a permission issue. Do you have access to a root user? If so, can you try not via sudo but with that user? I ask because my next guess is that maybe the permissions are not being transferred correctly with spawn.

**Comment by priscillapan** [comment]
i've already used root user before, error also.

**Comment by AndrewGuenther** [comment]
Can you comment with the permissions on `node_modules/jsdoc/jsdoc.js`?

Since the error is coming from spawn itself, I think that `jsdoc.js` isn't marked executable for some reason.

Try running:
```sh
chmod a+x node_modules/jsdoc/jsdoc.js
```

**Comment by priscillapan** [comment]
thank you!  jsdoc.js isn't marked executable.

**Comment by mlucool** [comment]
Good call @AndrewGuenther  thanks for solving this one 👍

**Comment by priscillapan** [comment]
@AndrewGuenther @mlucool  thanks for your help
