### ISSUE TITLE
Can't change the template

### ISSUE THREAD

**Issue by bleepbloopsify** [mlucool/gulp-jsdoc3#34]
This is my .jsdoc.json

{
    "tags": {
        "allowUnknownTags": true,
        "dictionaries": ["jsdoc", "closure"]
    },
    "opts": {
      "template":"minami",
      "encoding": "utf-8",
      "destination": "./docs/",
      "recurse": true
    },
    "templates":{
      "path":"minami"
    }
}

Why does it not resolve minami as the template?
It also does not work with values including
./node_modules/minami
when i set the layoutFile in templates.default to minami/tmpl/layout.tmpl it also does not work

**Comment by AndrewGuenther** [comment]
This issue has been fixed in master, but has not yet been released to npm.

@mlucool, any timeline on that?

**Comment by mlucool** [comment]
Published v1, closing. Please reopen if it's still an issue
