### ISSUE TITLE
Rewrite Docs in a Watch outputs duplicate content

### ISSUE THREAD

**Issue by sethkane** [mlucool/gulp-jsdoc3#36]
I am trying to build the jsdoc3 into my gulp process by not only building the documents on default but I want them to update as a developer is coding so they can see if the content is outputting correctly via browsersync.

The issue is that every time the code changes the jsdocs gets rewritten via a watch as a duplicate instead of a fresh document.  Each time the watch runs the exact content gets duplicated over and over again for as many times as the code has changed.

The first time the jsdocs is called everything works fine it is only when you call the task via a watch.  Here is my gulp to provide some context.

Is there a way to clear, flush or something else to make this more of a living document versus a one time build?

```
gulp.task('doc', function (cb) {
    gulp.src(['README.md', './src/js/**/*.es6.js'], {read: true})
        .pipe(jsdoc(jsdocConfig,cb));   
});
gulp.task('dev', function () {
    devCompiler.run(function (err, stats) {
        if (err) throw new gutil.PluginError('webpack:dev', err);
        reload();
    });
});
gulp.task('env', function () {
    browserSync({
        notify: true,
        port: 9000,
         ui: {
            port: 3000
        },
        server: {
            baseDir: ['./dist']
        }
    });

    var docs = browserSync.create()
    docs.init({
        notify: true,
        port: 9090,
        ui: {
            port: 9090
        },
        server: {
            baseDir: ['./docs']
        }
    });
    gulp.watch('./src/js/**/*.es6.js', ['lint','dev','doc']);
});

gulp.task('default', ['dev', 'doc', 'env']);
```

**Comment by mlucool** [comment]
Adding this library in watch will lead to problems because we are a thin wrapper over jsdoc. Until that supports watch natively, I don't think this will be much help. Please post a request for watch support here: https://github.com/jsdoc3/jsdoc/issues

Closing.

**Comment by sttk** [comment]
@mlucool It is seemed that this cause due to [this part](https://github.com/mlucool/gulp-jsdoc3/blob/master/src/gulp-jsdoc.js#L58-L59), and I think it would be good to clear `jsdocConfig.source.include` in the event listners of 'close' and 'error'.

I'm sorry if this is not correct, but I'm encountering the same as this issue.

**Comment by kevincolten** [comment]
@sttk is correct.  I think cloning `jsdocConfig` would fix the issue.

**Comment by kevincolten** [comment]
I've submitted a PR. Let me know what you think

**Comment by mlucool** [comment]
Thanks for the PR, I'll merge pending my comment
