### ISSUE TITLE
Cannot use config file

### ISSUE THREAD

**Issue by iredjee** [mlucool/gulp-jsdoc3#46]
After jsdoc update 3.4.2 -> 3.5.0 the following error comes out to console
```
Cannot use config file C:\Users\...\AppData\Local\Temp\tmp-74120Pc6ecFXqFbwS.tmp.
Only .js and .json files are supported.
```

**Comment by truetamtam** [comment]
Same error.

**Comment by iredjee** [comment]
It creates `.tmp` file and tries to parse it while jsdoc v3.5.0 added check for file extension https://github.com/jsdoc3/jsdoc/blob/master/cli.js#L99 . That's the reason

**Comment by Reinmar** [comment]
Same here. It shouldn't be released in a minor version of JSDoc but I can see how it slipped.

**Comment by Reinmar** [comment]
Hm... but this issue is already fixed on JSDoc side and should work fine with JSDoc 3.5.1 (https://github.com/jsdoc3/jsdoc/issues/1391) which was released 13 hours ago: https://github.com/jsdoc3/jsdoc/tree/3.5.1.

**Comment by iredjee** [comment]
@Reinmar yeah, just saw that issue is solved by jsdoc side, cool, closing this issue :)

**Comment by mlucool** [comment]
Thanks for solving this yourselves!
