### ISSUE TITLE
Cannot find module 'gulp-jsdoc3'

### ISSUE THREAD

**Issue by felixhayashi** [mlucool/gulp-jsdoc3#5]
Hi @mlucool,

thanks for picking up this project.

When running `npm install gulp-jsdoc3` and trying to include it in my gulp file I get an error saying `Cannot find module 'gulp-jsdoc3'`.

I looked inside `node_modules/gulp-jsdoc3` and it seems the `index.js` is missing…

Any ideas?

Thanks
Felix

**Comment by mlucool** [comment]
I am unable to reproduce this. What version of node/npm are you using? 

Can try to delete and reinstall? Maybe you ran out of space or the package didn't download correctly.

**Comment by felixhayashi** [comment]
The versions shipped by my distro are fairly old: npm: v1.3.10, nodejs: v0.10.25.

**Comment by felixhayashi** [comment]
> Can try to delete and reinstall? Maybe you ran out of space or the package didn't download correctly.

Did that already, didn't work. Other gulp packes work though.

**Comment by mlucool** [comment]
Using [tonic](https://tonicdev.com/npm/gulp-jsdoc3) I am unable to reproduce with v0.10.40.

Can you provide some way for me to reproduce?

**Comment by felixhayashi** [comment]
> Using tonic I am unable to reproduce with v0.10.40.

Hmm I see that. Strange. I tested on another computer also running Linux Mint 17 with the same node/npm packages installed and it also failed. – Really, no idea.

![2016-01-18 20 00 59](https://cloud.githubusercontent.com/assets/4307137/12400313/8a9fb290-be1f-11e5-8adb-80eb41520943.png)


The output of `$ ls node_modules/gulp-jsdoc3/` is

    dist  docs  node_modules  package.json  README.md  src

No index.js

**Comment by mlucool** [comment]
Try including it from git directly. I just pushed something that although should not be needed, would get around the bug that may be in your version.

**Comment by felixhayashi** [comment]
Will try. Wait a sec.

Did you see this: https://github.com/npm/npm/issues/5082

**Comment by felixhayashi** [comment]
Yes, index.js is now included

**Comment by mlucool** [comment]
Ok, I'll mark as closed now. By default anything listed as main is assumed to be in files, but likely you have a bug in your version. I'll re-release in the near future.

**Comment by felixhayashi** [comment]
Ehm, @mlucool, you won't believe: now the `dist` folder is missing.

**Comment by felixhayashi** [comment]
> Ok, I'll mark as closed now. By default anything listed as main is assumed to be in files, but likely you have a bug in your version. I'll re-release in the near future.

This is a bit crazy, I hope I can update my node/npm soon.

**Comment by felixhayashi** [comment]
Actually, where is the `dist` folder on your repo?

**Comment by mlucool** [comment]
Try 0.1.1 that I just released. Dist is build only for the release and not committed. Your version of npm seems to have quite a few bugs/issues. Current version of npm would have rebuild the project you depend on from git

**Comment by felixhayashi** [comment]
> Try 0.1.1 that I just released

:+1: Thanks works now.

>  Your version of npm seems to have quite a few bugs/issues. Current version of npm would have rebuild the project you depend on from git

Really? Well, I hope to get a chance to update soon…
