### ISSUE TITLE
Update to support gulp4

### ISSUE THREAD

**Issue by KenEucker** [mlucool/gulp-jsdoc3#52]
I wanted to use this package in my gulp pipeline, unfortunately it doesn't appear to work with gulp 4.

Steps to reproduce:
download this repository, in package.json change the gulp dependency to the following:
`"gulp": "gulpjs/gulp#v4.0.0"`

run `./node_modules/.bin/gulp`

and get the following error:
```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/keneucker/Downloads/gulp-jsdoc3-master/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/keneucker/Downloads/gulp-jsdoc3-master/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/keneucker/Downloads/gulp-jsdoc3-master/gulpfile.js:63:6)
```

**Comment by mlucool** [comment]
Thanks for your bug report Ken. This has not been tested with `gulp4`. Would you be open to making a merge request for support?

**Comment by KenEucker** [comment]
@mlucool sure sure. I have not yet upgraded a package from gulp3 to gulp4 yet but I will take a shot at it.

**Comment by KenEucker** [comment]
@mlucool hmm. It suppose I might be wrong about the package not working with gulp4. I updated the gulpfile with the following flag and method:

```
const runningGulp4 = gulp.series ? true : false;

...

const addGulpTask = function (taskName, task, dependencies = []) {
	if (runningGulp4) {
		gulp.task(taskName, gulp.series(...dependencies, task));
	} else {
		gulp.task(taskName, task);
	}
};

...

if (runningGulp4) {
	gulp.task('default', gulp.series('copy', 'build', 'doc'));
} else {
	addGulpTask('default', function (cb) {

		let runSequence = require('run-sequence');
		runSequence('copy', 'build', 'doc', cb);
	});
}
```

This allows the code in this repository to run using either gulp3 or gulp4 depending on whether or not gulp.series exists ( a `run-sequence` alternative method built into gulp4 ). I was able to test that this continues to function with both versions now. However, I am still running into the same issue when using this package in my gulp pipeline:

```
config.opts.readme = 'README.md';
config.source.include = ['./scripts/**/*.js'];

return gulp.src([config.opts.readme, config.source.include], { read: false })
	.pipe(jsdoc(config));
```

So the issue may not be gulp4 related like I had originally thought, unfortunately. Let me know if you'd still like a pull request with the modifications to the gulpfile making it work with gulp3 and gulp4. If I am able to determine what is causing the issue and it pertains to this package I will report back to this issue.

**Comment by KenEucker** [comment]
I've continued to dig around and have a little more information, but am not closer to a working solution.

I believe what is happening is that the gulp.src call ends before the jsdoc task succeeds, so my pipeline may be ending and thus the jsdoc task cannot complete. I haven't been able to completely confirm this suspicion, but I do think that this may be a root cause of my problem. 

I can use the same configuration and run jsdoc from the command line and it works fine.

**Comment by KenEucker** [comment]
I haven't been able to fully determine why I can't get jsdoc to work with my project, but I also don't like that gulp-jsdoc uses child exec to run jsdoc and would prefer that gulp packages in my application use code within the same process. I've now discovered that there is a programmable API for jsdoc:
https://github.com/jsdoc2md/jsdoc-api

I am going to switch to the jsdoc-api as an alternative. Cheers,
