### ISSUE TITLE
Node.js 12 support

### ISSUE THREAD

**Issue by Itee** [mlucool/gulp-jsdoc3#54]
Hello,

The current version of jsdoc include in this package is 3.4.1 but it is broken under node v12.

To fix this you need to update jsdoc to v3.6.0.

Here a topic about this issue: [Node.js 12 support](https://github.com/hegemonic/requizzle/issues/5)

Best regards.

**Comment by mlucool** [comment]
Thanks. The package.json says: `"jsdoc": "^3.4.1"`, which includes 3.6.0. You can try clearing your package-lock.json or yarn.lock and reinstalling to get a later version.

See: https://semver.npmjs.com/

**Comment by Itee** [comment]
It work well.

Thanks a lot !
