### ISSUE TITLE
Any particular reason why you decided to bundle/force the ink-docstrap template?

### ISSUE THREAD

**Issue by kdelmonte** [mlucool/gulp-jsdoc3#6]
If not, I would like to submit a PR with this bundle eliminated.

**Comment by mlucool** [comment]
It's the best lib for output IMO. What would you suggest otherwise? I would be open to a PR that give you the option to disable it, but I do think it is a nice default.

**Comment by mlucool** [comment]
Closed via https://github.com/mlucool/gulp-jsdoc3/pull/7
