### ISSUE TITLE
Error while executing simple example

### ISSUE THREAD

**Issue by 5ika** [mlucool/gulp-jsdoc3#9]
Gulp doc task returns an error while executing this test code :

```javascript
var jsdoc = require('gulp-jsdoc3');
gulp.task('doc', function (cb) {
  gulp.src('source/js/**/*.js', {read: false})
      .pipe(jsdoc(cb));
});
```

```
Cannot parse the config file /tmp/tmp-7055paabrxtXIJt8.tmp: SyntaxError: Unexpected token u
```

But I can't see the temporary file content because it is automatically removed.

**Comment by mlucool** [comment]
Try:
```.pipe(jsdoc(undefined, cb));````

If that is the issue, it is fixed for the next version to be released in ~1 week

**Comment by 5ika** [comment]
Okay, that's works ! Thank you
